### ISSUE TITLE
Add an applications.properties file to test/resources so that we can run backend tests that ignore your data.sql file

### ISSUE THREAD

**Issue by sethvanb** [ucsb-cs156-f20/proj-ucsb-cs-las#59]
- [x] applications.properties file is under test/resources
- [x] running backend tests will ignore data.sql (no error occurs)

**Comment by scottpchow23** [comment]
Reopening this issue because the PR has not yet been merged into `main`. Could we clarify what tests would need to ignore the `data.sql` file? We don't typically write tests that communicate to a live running database.
